import type {
  CaptureBrief,
  DecisionAction,
  HumanDecision,
  NoticeSnapshot,
} from "@/lib/types";

export function buildBriefMarkdown({
  snapshot,
  brief,
  decision,
  decisionActions,
}: {
  snapshot: NoticeSnapshot;
  brief: CaptureBrief;
  decision: HumanDecision | null;
  decisionActions: DecisionAction[];
}): string {
  const gates = brief.gates
    .map((gate) => `- **${gate.label}** (${gate.state}): ${gate.explanation}`)
    .join("\n");
  const actions = decisionActions
    .map((action) => `- [${action.status}] ${action.title} — ${action.detail}`)
    .join("\n");

  return [
    `# Capture brief · ${snapshot.title.value ?? "Federal opportunity"}`,
    "",
    `- Agency: ${snapshot.agency.value ?? "Not stated"}`,
    `- Solicitation: ${snapshot.solicitationNumber.value ?? "Not stated"}`,
    `- Notice: ${snapshot.sourceUrl}`,
    `- Readiness: ${brief.readiness} — ${brief.readinessReason}`,
    `- Decision: ${decision ?? "Not decided"}`,
    "",
    "## Executive summary",
    brief.executiveSummary,
    "",
    "## Hard gates",
    gates,
    "",
    "## Strongest reasons",
    ...brief.strongestReasons.map((item) => `- ${item}`),
    "",
    "## Largest risks",
    ...brief.largestRisks.map((item) => `- ${item}`),
    "",
    "## Next actions",
    ...brief.nextActions.map((item, index) => `${index + 1}. ${item}`),
    "",
    ...(decision
      ? ["## Decision packet", actions || "- No actions recorded", ""]
      : []),
    "_Generated by CaptureBrief · Exa-backed · human decision required_",
  ].join("\n");
}
